/*******************************************************************************
 * Copyright (c) 2004 - 2019 CPB Software AG
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS".
 * IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY
 * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES.
 *
 * This software is published under the Apache License, Version 2.0, January 2004, 
 * http://www.apache.org/licenses/
 *  
 * Author: Florin Bogdan Balint
 *******************************************************************************/

package com.nagoya.model.blockchain;

import java.io.Serializable;
import java.util.Map;
import java.util.TreeMap;

/**
 * Abstract class representing an asset.
 * 
 * @author flba
 *
 */
public class Asset implements Serializable {

    private static final long   serialVersionUID = 1L;

    private String              amount;

    /**
     * The ID which was generated by the blockchain when the asset was last transferred (or created).
     */
    private String              txIdAssetOperation;

    private String              txIdAssetConfirmation;

    /**
     * The ID which was generated by the blockchain when the asset was created.
     */
    private String              txIdAssetCreation;

    /**
     * This data will be persisted permanently in the blockchain.
     */
    private Map<String, Object> assetData        = new TreeMap<>();

    /**
     * This data can be updated in the blockchain.
     */
    private Map<String, String> metaData         = new TreeMap<>();

    /**
     * @return the txIdAssetOperation
     */
    public String getTxIdAssetOperation() {
        return txIdAssetOperation;
    }

    /**
     * @param txIdAssetOperation the txIdAssetOperation to set
     */
    public void setTxIdAssetOperation(String txIdAssetOperation) {
        this.txIdAssetOperation = txIdAssetOperation;
    }

    /**
     * @return the txIdAssetCreation
     */
    public String getTxIdAssetCreation() {
        return txIdAssetCreation;
    }

    /**
     * @param txIdAssetCreation the txIdAssetCreation to set
     */
    public void setTxIdAssetCreation(String txIdAssetCreation) {
        this.txIdAssetCreation = txIdAssetCreation;
    }

    /**
     * @return the amount
     */
    public String getAmount() {
        return amount;
    }

    /**
     * @param amount the amount to set
     */
    public void setAmount(String amount) {
        this.amount = amount;
    }

    /**
     * @return the assetData
     */
    public Map<String, Object> getAssetData() {
        return assetData;
    }

    /**
     * @param assetData the assetData to set
     */
    public void setAssetData(Map<String, Object> assetData) {
        this.assetData = assetData;
    }

    /**
     * @return the metaData
     */
    public Map<String, String> getMetaData() {
        return metaData;
    }

    /**
     * @param metaData the metaData to set
     */
    public void setMetaData(Map<String, String> metaData) {
        this.metaData = metaData;
    }

    /**
     * @return the txIdAssetConfirmation
     */
    public String getTxIdAssetConfirmation() {
        return txIdAssetConfirmation;
    }

    /**
     * @param txIdAssetConfirmation the txIdAssetConfirmation to set
     */
    public void setTxIdAssetConfirmation(String txIdAssetConfirmation) {
        this.txIdAssetConfirmation = txIdAssetConfirmation;
    }

}
