/*******************************************************************************
 * Copyright (c) 2004 - 2019 CPB Software AG
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS".
 * IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY
 * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES.
 *
 * This software is published under the Apache License, Version 2.0, January 2004, 
 * http://www.apache.org/licenses/
 *  
 * Author: Florin Bogdan Balint
 *******************************************************************************/

package com.nagoya.model.dbo.contract;

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;

import org.hibernate.envers.Audited;
import org.hibernate.envers.NotAudited;

import com.nagoya.model.dbo.DBO;
import com.nagoya.model.dbo.resource.GeneticResourceDBO;

/**
 * A contract is concluded for one or more resources. This class represents the connection in between.
 * 
 * @author flba
 *
 */
@Audited
@Entity(name = "tcontract_resource")
public class ContractResourceDBO extends DBO {

    private static final long  serialVersionUID = 1L;

    @NotAudited
    @OneToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "genetic_resource_id")
    private GeneticResourceDBO geneticResource;

    @Column(name = "amount")
    private BigDecimal         amount;

    @Column(name = "measuring_unit")
    private String             measuringUnit;

    /**
     * When the genetic resource is saved as an asset into the database, then a transaction id is generated by the blockchain.
     */
    @Column(name = "tx_id")
    private String             transactionId;

    public GeneticResourceDBO getGeneticResource() {
        return geneticResource;
    }

    public void setGeneticResource(GeneticResourceDBO geneticResource) {
        this.geneticResource = geneticResource;
    }

    public BigDecimal getAmount() {
        return amount;
    }

    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    public String getMeasuringUnit() {
        return measuringUnit;
    }

    public void setMeasuringUnit(String measuringUnit) {
        this.measuringUnit = measuringUnit;
    }

    /**
     * @return the transactionId
     */
    public String getTransactionId() {
        return transactionId;
    }

    /**
     * @param transactionId the transactionId to set
     */
    public void setTransactionId(String transactionId) {
        this.transactionId = transactionId;
    }

}
